operator:
  serviceAccountName: null
  image:
    repository: null
    tag: null  
ubbagent:
  image: null
billingagent:
  image: us-central1-docker.pkg.dev/proven-reality-226706/redis-market-place/billing-agent:6.0.12-5
usagemeter:
  image: us-central1-docker.pkg.dev/proven-reality-226706/redis-market-place/usage-meter:6.0.12-5
