steps:
- name: gcr.io/cloud-builders/docker
  id: docker-build-push
  entrypoint: bash
  args:
  - '-c'
  - |
    echo gcr.io/${PROJECT_ID}/redislabs/deployer  
    export maxver=`docker image ls gcr.io/${PROJECT_ID}/redislabs/deployer  | tr -s " " | cut -d" " -f 2 | tail -n +2 |   grep -o "1\.[0-9][0-9]*" | cut -d"." -f2 | sort -n -r | head -n 1`
    export newver=`echo "1.$(($maxver +1 ))"`
    echo  'new version' $newver 'from' $maxver
    docker build --build-arg REGISTRY=gcr.io/${PROJECT_ID}/redislabs --build-arg TAG=${newver} --build-arg MARKETPLACE_TOOLS_TAG="0.7.9" --tag gcr.io/${PROJECT_ID}/redislabs/deployer:${newver} -f deployer/Dockerfile .
    docker push gcr.io/${PROJECT_ID}/redislabs/deployer:${newver}
    docker pull redislabs/operator:${TAG_NAME}
    docker tag redislabs/operator:${TAG_NAME} gcr.io/${PROJECT_ID}/redislabs:${newver}
    docker push gcr.io/${PROJECT_ID}/redislabs:${newver}

options:
  substitution_option: 'ALLOW_LOOSE'
