steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '--build-arg', 'REGISTRY=gcr.io/proven-reality-226706/redislabs', '--build-arg', 'TAG="${TAG_NAME}"' , '--build-arg', 'MARKETPLACE_TOOLS_TAG="0.7.9"', '--tag', 'gcr.io/proven-reality-226706/redislabs/deployer:${TAG_NAME}', '-f', 'deployer/Dockerfile', '.']

- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/proven-reality-226706/redislabs/deployer:${TAG_NAME}']

- name: 'gcr.io/cloud-builders/docker'
  args: ['pull', 'redislabs/operator:5.4.6-1183']

# point from source to target
- name: 'gcr.io/cloud-builders/docker'
  args: ['tag', 'redislabs/operator:5.4.6-1183', 'gcr.io/proven-reality-226706/redislabs:${TAG_NAME}']

# my image is pushed to Container Registry
images: [ 'gcr.io/proven-reality-226706/redislabs:${TAG_NAME}']


options:
  substitution_option: 'ALLOW_LOOSE'
