steps:
- name: gcr.io/cloud-builders/docker
  id: docker-build-push
  entrypoint: bash
  args:
  - '-c'
  - |
    export maxver=`docker image ls gcr.io/proven-reality-226706/redislabs/deployer  | tr -s " "|cut -d" " -f 2 |tail -n +2 |   grep -o "1\.[0-9][0-9]*" |cut -d"." -f2|sort -n -r |head -n 1  `
    export newver=`echo "1.$(($maxver +1 ))"`
    echo $newver 'from' $maxver
    docker build --build-arg REGISTRY=gcr.io/${PROJECT_ID}/redislabs --build-arg TAG=${newver} --build-arg MARKETPLACE_TOOLS_TAG="0.7.9" --tag gcr.io/${PROJECT_ID}/redislabs/deployer:${newver} -f deployer/Dockerfile .
    docker push gcr.io/${PROJECT_ID}/redislabs/deployer:${newver}
    docker pull redislabs/operator:${_OP_VERSION}
    docker tag redislabs/operator:${_OP_VERSION} gcr.io/${PROJECT_ID}/redislabs:${newver}
    docker push gcr.io/${PROJECT_ID}/redislabs:${newver}


substitutions:
  _OP_VERSION: "5.4.6-1183"

options:
  substitution_option: 'ALLOW_LOOSE'
