kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: testapp
rules:
  - apiGroups: ["apps"]
    resources: ["deployments"]
    verbs: ["*"]
  - apiGroups: ["app.k8s.io"]
    resources: ["applications"]
    verbs: ["*"]
  - apiGroups: [""]
    resources: ["services", "secrets"]
    verbs: ["*"]
