kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: testapp
subjects:
- kind: ServiceAccount
  name: default
- kind: ServiceAccount
  name: redis-enterprise-operator
roleRef:
  kind: Role
  name: testapp
  apiGroup: rbac.authorization.k8s.io
