apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "redis_operator.DeploymentName" . }}
  namespace: {{ .Release.Namespace }} # In Helm Jaeger, this is missing
  labels:
    app.kubernetes.io/name: "{{ .Release.Name }}"
    app.kubernetes.io/component: operator
spec:
  replicas: 1
  selector:
    matchLabels:
      name: {{ template "redis_operator.DeploymentName" . }}
  template:
    metadata:
      labels:
        name: {{ template "redis_operator.DeploymentName" . }}
        app.kubernetes.io/name: "{{ .Release.Name }}"
        app.kubernetes.io/component: operator
    spec:
      serviceAccountName: {{ .Values.operator.serviceAccountName }}
      initContainers:
        {{- include "initContainerWaitForCRDsDeploy" . | nindent 6 }}
      containers:
        - name: redis-enterprise-operator
          image: {{ .Values.operator.image.repository }}:{{ .Values.operator.image.tag }}
          command:
            - redis-enterprise-operator
          imagePullPolicy: Always
          env:
            - name: WATCH_NAMESPACE
              # In Helm  Jaeger, value is just "". But in old RedisOperator and old Jaeger, we have value from fieldRef from metadata.namespace
              value: ""
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: OPERATOR_NAME
              value: "{{ template "redis_operator.DeploymentName" . }}"
