apiVersion: v1
kind: Service
metadata:
  labels:
    app: redis-enterprise
    app.kubernetes.io/name: redis-enterprise-operator
  name: admission
spec:
  ports:
  - port: 443
    protocol: TCP
    targetPort: 8443
  selector:
    name: redis-enterprise-operator
