apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "redis_operator.CRsConfigMap" . }}
  labels:
    app.kubernetes.io/name: {{ .Release.Name }}
    app.kubernetes.io/component: cr-configmap
data:
  redis-enterprise-cluster.yaml: |-
    apiVersion: "app.redislabs.com/v1"
    kind: "RedisEnterpriseCluster"
    metadata:
      name: "redis-enterprise"
      namespace: {{ .Release.Namespace }}
      labels:
        app.kubernetes.io/name: "{{ .Release.Name }}"
    spec:
      extraLabels:
        app.kubernetes.io/name: "{{ .Release.Name }}"
      podAnnotations:
        app.kubernetes.io/name: "{{ .Release.Name }}"
      nodes: {{ .Values.operator.replicas }}
      persistentSpec:
        enabled: true
        storageClassName: {{ .Values.operator.storageClass }}
      uiServiceType: "{{ if .Values.ingressAvailable -}}LoadBalancer{{- else -}}ClusterIP{{- end }}"
      username: "{{ .Values.operator.redisAdmin }}"
      redisEnterpriseNodeResources:
        limits:
          cpu: "{{ .Values.operator.nodeCpu }}m"
          memory: "{{ .Values.operator.nodeMem }}Gi"
        requests:
          cpu: "{{ .Values.operator.nodeCpu }}m"
          memory: "{{ .Values.operator.nodeMem }}Gi"


