---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: redis-enterprise-operator
  namespace: {{ .Release.Namespace }}
rules:
- apiGroups: ["", "extensions", "apps", "rbac.authorization.k8s.io", "policy"]
  resources: ["*"]
  verbs: ["*"]
- apiGroups:
  - app.redislabs.com
  resources: ["*"]
  verbs: ["*"]
---
kind: ServiceAccount
apiVersion: v1
metadata:
  name:  {{ .Values.operator.serviceAccountName }}
  namespace: {{ .Release.Namespace }}
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: redis-enterprise-operator
  namespace: {{ .Release.Namespace }}
subjects:
- kind: ServiceAccount
  name: {{ .Values.operator.serviceAccountName }}
  namespace: {{ .Release.Namespace }}
roleRef:
  kind: Role
  name: redis-enterprise-operator
  apiGroup: rbac.authorization.k8s.io
