apiVersion: app.k8s.io/v1beta1
kind: Application #TODO The CRD is supposed to pause before creating this application, but the sleep process is concurrent with applying this K8s object, so we find that the CRD is not yet available
metadata:
  name: "{{ .Release.Name }}"
  annotations:
    kubernetes-engine.cloud.google.com/icon: >-
      data:image/png;base64, {{ .Files.Get "logo.png" | b64enc }} {{/* Get logo.png from the root of chart */}}
    marketplace.cloud.google.com/deploy-info: '{"partner_id": "redislabs-public", "product_id": {{ .Chart.Name | quote }}, "partner_name": "Redis Labs"}'
  labels:
    app.kubernetes.io/name: "{{ .Release.Name }}"
spec:
  descriptor:
    type: Redis Enterprise Operator
    version: {{ .Values.operator.image.tag | quote }}
    description: |-
      Redis Operator makes it easy to deploy and manage Redis Enterprise
      on Kubernetes.
    maintainers:
    - name: Redis Labs
      url: https://redislabs.com/company/contact/support/
    links:
    - description: 'User Guide: Redis Enterprise'
      url: https://support.redislabs.com
    notes: |-
      See more details and manual installation instructions here https://github.com/RedisLabs/gkemarketplace
  selector:
    matchLabels:
      app.kubernetes.io/name: "{{ .Release.Name }}"
  componentKinds:
  - group: apps/v1
    kind: Deployment
  - group: v1
    kind: ConfigMap
  - group: v1
    kind: ServiceAccount
  - group: v1
    kind: Job
  - group: v1
    kind: Pod
  - group: v1
    kind: Job
  - group: v1
    kind: Service
  - group: apps/v1
    kind: StatefulSet
